# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QMainWindow, QWidget, QLabel, QPushButton, QLineEdit \
                            , QDateTimeEdit, QApplication

from PyQt5.QtCore import QRect, QDate, QTime
from PyQt5.QtGui import QFont, QIntValidator

import static.staticValues as staticValues

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.resize(773, 452)

        #메인 화면 색상py
        self.setStyleSheet("color: black;"
                        "background-color: white")

        font = QFont()
        font.setFamily("NanumGothic")
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QRect(30, 20, 181, 51))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.edit_filePath = QLineEdit(self.centralwidget)
        self.edit_filePath.setGeometry(QRect(60, 80, 551, 21))
        self.edit_filePath.setInputMask("")
        self.edit_filePath.setReadOnly(True)
        self.edit_key = QLineEdit(self.centralwidget)
        self.edit_key.setGeometry(QRect(200, 170, 411, 21))
        self.edit_secret_key = QLineEdit(self.centralwidget)
        self.edit_secret_key.setGeometry(QRect(200, 210, 411, 21))
        # self.edit_token = QLineEdit(self.centralwidget)
        # self.edit_token.setGeometry(QRect(200, 210, 411, 21))
        self.button_file = QPushButton(self.centralwidget)
        self.button_file.setGeometry(QRect(630, 77, 93, 28))
        
        #버튼 스타일 변경
        self.button_file.setStyleSheet(staticValues.grayButtonStyleSheet)
        self.button_file.setFont(staticValues.buttonFont)

        font = QFont()
        font.setFamily("NanumGothic")
        self.button_file.setFont(font)

        self.button_getToken = QPushButton(self.centralwidget)
        self.button_getToken.setGeometry(QRect(630, 205, 93, 28))
        
        #버튼 스타일 변경
        self.button_getToken.setStyleSheet(staticValues.blueButtonStyleSheet)
        self.button_getToken.setFont(staticValues.buttonFont)

        font = QFont()
        font.setFamily("NanumGothic")
        self.button_getToken.setFont(font)

        # self.button_getAuthToken = QPushButton(self.centralwidget)
        # self.button_getAuthToken.setGeometry(QRect(630, 205, 93, 28))
        
        # #버튼 스타일 변경
        # self.button_getAuthToken.setStyleSheet(staticValues.blueButtonStyleSheet)
        # self.button_getAuthToken.setFont(staticValues.buttonFont)

        # font = QFont()
        # font.setFamily("NanumGothic")
        # self.button_getAuthToken.setFont(font)
        
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setGeometry(QRect(60, 172, 100, 15))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setGeometry(QRect(60, 212, 120, 15))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setGeometry(QRect(60, 131, 500, 16))
        # font = QFont()
        # font.setFamily("NanumGothic")
        # font.setBold(True)
        # font.setWeight(75)
        # self.label_4.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setGeometry(QRect(60, 270, 101, 16))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setGeometry(QRect(80, 312, 101, 16))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setGeometry(QRect(80, 352, 101, 16))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.dateTime_upload = QDateTimeEdit(self.centralwidget)
        self.dateTime_upload.setGeometry(QRect(200, 310, 194, 22))

        #오늘 날짜 세팅
        self.dateTime_upload.setDate(QDate.currentDate())
        self.dateTime_upload.setTime(QTime.currentTime())
        
        self.edit_period = QLineEdit(self.centralwidget)
        self.edit_period.setGeometry(QRect(200, 350, 90, 21))

        #가로/세로 입력창 숫자만 입력하도록 수정
        self.edit_period.setValidator(QIntValidator(1, 1440))

        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setGeometry(QRect(310, 353, 64, 15))
        self.button_write = QPushButton(self.centralwidget)
        self.button_write.setGeometry(QRect(180, 400, 391, 28))

        #버튼 스타일 변경
        self.button_write.setStyleSheet(staticValues.grayButtonStyleSheet)
        self.button_write.setFont(staticValues.buttonFont)
        self.button_write.setEnabled(False)
        
        self.label_countdown = QLabel(self.centralwidget)
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(False)
        font.setWeight(10)
        self.label_countdown.setFont(font)
        self.label_countdown.setText(str(0))
        self.label_countdown.setGeometry(QRect(610, 400, 50, 22))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("AuTwitt")
        self.label.setText("AuTwitt")
        self.edit_filePath.setPlaceholderText("문단 파일 경로")
        self.button_file.setText("파일 열기")
        self.button_getToken.setText("인증")
        # self.button_getAuthToken.setText("인증")
        self.label_2.setText("APP_KEY")
        self.label_3.setText("SECRET_KEY")
        self.label_4.setText('<a href="https://apps.twitter.com">KEY 신청하기</a>')
        self.label_4.setOpenExternalLinks(True)
        self.label_5.setText("게시 시간 설정")
        self.label_6.setText("게시 시작 날짜")
        self.label_7.setText("게시 주기")
        self.edit_period.setPlaceholderText("분단위 주기")
        self.label_8.setText("분")
        self.button_write.setText("자동 등록 시작")


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
